/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeedatabase;

import java.awt.event.KeyEvent;

/**
 * employee database/management system
 * allows a human resources manager to track employees in a company
 * created for ICS4U0
 * @author alan
 */
public class MainComponent extends javax.swing.JFrame {
    /**
     * Creates new form DashboardComponent
     */
    public MainComponent() {
        initComponents();
        initializeDatabase();
        initializeComponents();
        updateDashboard();
    }
    
    /**
     * initializes global variables
     */
    private AddEmployeeComponent addEmployeeComponent;
    private ColorSelectorService colorSelector = new ColorSelectorService();
    private HashTable employeeDatabase = new HashTable(2);
    
    /**
     * initialize database with employees
     */
    private void initializeDatabase() {
        PartTimeEmployee newEmployee1 = new PartTimeEmployee(1, "A", "A1", 0, 0, 0.0, 0.0, 0.0, 0.0);
        PartTimeEmployee newEmployee2 = new PartTimeEmployee(2, "A", "A1", 0, 0, 0.0, 0.0, 0.0, 0.0);
        PartTimeEmployee newEmployee3 = new PartTimeEmployee(3, "A", "A1", 0, 0, 0.0, 0.0, 0.0, 0.0);
        PartTimeEmployee newEmployee4 = new PartTimeEmployee(4, "A", "A1", 0, 0, 0.0, 0.0, 0.0, 0.0);
        FullTimeEmployee newEmployee5 = new FullTimeEmployee(5, "A", "A1", 0, 0, 0.0, 0.0);
        FullTimeEmployee newEmployee6 = new FullTimeEmployee(6, "A", "A1", 0, 0, 0.0, 0.0);
        FullTimeEmployee newEmployee7 = new FullTimeEmployee(7, "A", "A1", 0, 0, 0.0, 0.0);

        employeeDatabase.addEmployee(newEmployee1);
        employeeDatabase.addEmployee(newEmployee7);
        employeeDatabase.addEmployee(newEmployee3);
        employeeDatabase.addEmployee(newEmployee2);
        employeeDatabase.addEmployee(newEmployee5);
        employeeDatabase.addEmployee(newEmployee6);
        employeeDatabase.addEmployee(newEmployee4);
    }
    
    /**
     * initializes other components
     */
    private void initializeComponents() {
        addEmployeeComponent = new AddEmployeeComponent();
        addEmployeeComponent.confirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEmployeeConfirmButtonMouseClicked(evt);
            }
        });
        addEmployeeComponent.confirmButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmButtonKeyPressed(evt);
            }
        });
    }
    
    /**
     * updates the dashboard view
     */
    private void updateDashboard() {
        // update the number of employees
        if (employeeDatabase.getNumBuckets() == 1) {
            information.setText("there is currently 1 employee.");
        } else {
            information.setText("there are currently " + employeeDatabase.getNumEmployees() + " employees.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        information = new javax.swing.JLabel();
        addEmployeeButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        dashboardPanel.setBackground(new java.awt.Color(250, 250, 250));
        dashboardPanel.setForeground(new java.awt.Color(0, 0, 0));
        dashboardPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dashboardPanel.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        dashboardPanel.setSize(new java.awt.Dimension(720, 480));

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Montserrat", 0, 30)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("employee database");

        information.setBackground(new java.awt.Color(255, 255, 255));
        information.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        information.setForeground(new java.awt.Color(0, 0, 0));
        information.setText("there are currently 0 employees.");

        addEmployeeButton.setBackground(new java.awt.Color(230, 230, 230));
        addEmployeeButton.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        addEmployeeButton.setForeground(new java.awt.Color(0, 0, 0));
        addEmployeeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addEmployeeButton.setText("add employee");
        addEmployeeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addEmployeeButton.setMaximumSize(new java.awt.Dimension(125, 35));
        addEmployeeButton.setMinimumSize(new java.awt.Dimension(125, 35));
        addEmployeeButton.setOpaque(true);
        addEmployeeButton.setPreferredSize(new java.awt.Dimension(125, 35));
        addEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addEmployeeButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addEmployeeButtonMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEmployeeButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addEmployeeButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addEmployeeButtonMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title)
                    .addComponent(information))
                .addContainerGap(369, Short.MAX_VALUE))
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(information)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(324, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(dashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEmployeeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeeButtonMouseEntered
        // TODO add your handling code here:
        addEmployeeButton.setBackground(colorSelector.button_hover);
    }//GEN-LAST:event_addEmployeeButtonMouseEntered

    private void addEmployeeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeeButtonMouseExited
        // TODO add your handling code here:
        addEmployeeButton.setBackground(colorSelector.button_background);
    }//GEN-LAST:event_addEmployeeButtonMouseExited

    private void addEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeeButtonMouseClicked
        // TODO add your handling code here:
        addEmployeeComponent.reset();
        addEmployeeComponent.updateDisplay();
        addEmployeeComponent.setVisible(true);
    }//GEN-LAST:event_addEmployeeButtonMouseClicked

    private void addEmployeeButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeeButtonMousePressed
        // TODO add your handling code here:
        addEmployeeButton.setBackground(colorSelector.button_pressed);
    }//GEN-LAST:event_addEmployeeButtonMousePressed

    private void addEmployeeButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeeButtonMouseReleased
        // TODO add your handling code here:
        addEmployeeButton.setBackground(colorSelector.button_background);
    }//GEN-LAST:event_addEmployeeButtonMouseReleased
    
    private void addEmployeeConfirmButtonMouseClicked(java.awt.event.MouseEvent evt) {                                               
        // TODO add your handling code here:
        checkNewEmployee();
    }
    
    private void confirmButtonKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            checkNewEmployee();
        }
    }                                         
    
    private void checkNewEmployee() {
        // add employee and reset fields
        
        boolean errorsExist = addEmployeeComponent.checkErrors();
        
        if (!errorsExist) {
            FullTimeEmployee newEmployee = new FullTimeEmployee(7, "A", "A1", 0, 0, 0.0, 0.0);
            employeeDatabase.addEmployee(newEmployee);
            addEmployeeComponent.reset();
        }
        
        addEmployeeComponent.updateDisplay();
        updateDashboard();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>z
        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainComponent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addEmployeeButton;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JLabel information;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
